title: Dominik Arnold
description: Digital transformation, IoT, AI, cloud, and growth.
url: "https://www.domarn.de"
baseurl: ""

markdown: kramdown
permalink: pretty

kramdown:
  input: Kramdown

collections:
  sections:
    output: false

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - AGENTS.md
